{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "b6ee09c4",
   "metadata": {},
   "outputs": [],
   "source": [
    "# import Pandas\n",
    "import pandas as pd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "67a7e1a5",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Name</th>\n",
       "      <th>Annual</th>\n",
       "      <th>Sick</th>\n",
       "      <th>Personal</th>\n",
       "      <th>Bonus</th>\n",
       "      <th>Total leave taken</th>\n",
       "      <th>Total leave available</th>\n",
       "      <th>Annual total</th>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Personnel_ID</th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "      <th></th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>215</th>\n",
       "      <td>Shen Lee</td>\n",
       "      <td>23</td>\n",
       "      <td>10</td>\n",
       "      <td>5</td>\n",
       "      <td>3</td>\n",
       "      <td>0</td>\n",
       "      <td>38</td>\n",
       "      <td>38</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>216</th>\n",
       "      <td>Leon Buhle</td>\n",
       "      <td>20</td>\n",
       "      <td>8</td>\n",
       "      <td>4</td>\n",
       "      <td>0</td>\n",
       "      <td>3</td>\n",
       "      <td>32</td>\n",
       "      <td>35</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>217</th>\n",
       "      <td>Tracy Adams</td>\n",
       "      <td>15</td>\n",
       "      <td>10</td>\n",
       "      <td>5</td>\n",
       "      <td>0</td>\n",
       "      <td>5</td>\n",
       "      <td>30</td>\n",
       "      <td>35</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>218</th>\n",
       "      <td>Lebo Sinuka</td>\n",
       "      <td>19</td>\n",
       "      <td>9</td>\n",
       "      <td>0</td>\n",
       "      <td>3</td>\n",
       "      <td>10</td>\n",
       "      <td>28</td>\n",
       "      <td>38</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>219</th>\n",
       "      <td>Lauren Pierce</td>\n",
       "      <td>21</td>\n",
       "      <td>7</td>\n",
       "      <td>5</td>\n",
       "      <td>3</td>\n",
       "      <td>5</td>\n",
       "      <td>33</td>\n",
       "      <td>38</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>220</th>\n",
       "      <td>Monika Bond</td>\n",
       "      <td>21</td>\n",
       "      <td>10</td>\n",
       "      <td>2</td>\n",
       "      <td>6</td>\n",
       "      <td>8</td>\n",
       "      <td>33</td>\n",
       "      <td>41</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>221</th>\n",
       "      <td>Natahs Allsopp</td>\n",
       "      <td>10</td>\n",
       "      <td>9</td>\n",
       "      <td>5</td>\n",
       "      <td>0</td>\n",
       "      <td>11</td>\n",
       "      <td>24</td>\n",
       "      <td>35</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>222</th>\n",
       "      <td>Nicolas Winter</td>\n",
       "      <td>15</td>\n",
       "      <td>10</td>\n",
       "      <td>4</td>\n",
       "      <td>3</td>\n",
       "      <td>9</td>\n",
       "      <td>29</td>\n",
       "      <td>38</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>223</th>\n",
       "      <td>Christopher Eckson</td>\n",
       "      <td>16</td>\n",
       "      <td>8</td>\n",
       "      <td>2</td>\n",
       "      <td>6</td>\n",
       "      <td>15</td>\n",
       "      <td>26</td>\n",
       "      <td>41</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>224</th>\n",
       "      <td>Siobhan O'Malley</td>\n",
       "      <td>23</td>\n",
       "      <td>5</td>\n",
       "      <td>5</td>\n",
       "      <td>3</td>\n",
       "      <td>5</td>\n",
       "      <td>33</td>\n",
       "      <td>38</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                            Name  Annual  Sick  Personal  Bonus  \\\n",
       "Personnel_ID                                                      \n",
       "215                     Shen Lee      23    10         5      3   \n",
       "216                   Leon Buhle      20     8         4      0   \n",
       "217                  Tracy Adams      15    10         5      0   \n",
       "218                  Lebo Sinuka      19     9         0      3   \n",
       "219                Lauren Pierce      21     7         5      3   \n",
       "220                  Monika Bond      21    10         2      6   \n",
       "221               Natahs Allsopp      10     9         5      0   \n",
       "222               Nicolas Winter      15    10         4      3   \n",
       "223           Christopher Eckson      16     8         2      6   \n",
       "224             Siobhan O'Malley      23     5         5      3   \n",
       "\n",
       "              Total leave taken  Total leave available  Annual total  \n",
       "Personnel_ID                                                          \n",
       "215                           0                     38            38  \n",
       "216                           3                     32            35  \n",
       "217                           5                     30            35  \n",
       "218                          10                     28            38  \n",
       "219                           5                     33            38  \n",
       "220                           8                     33            41  \n",
       "221                          11                     24            35  \n",
       "222                           9                     29            38  \n",
       "223                          15                     26            41  \n",
       "224                           5                     33            38  "
      ]
     },
     "execution_count": 12,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# define the dictionary\n",
    "data = {'Name' : ['Shen Lee', 'Leon Buhle', 'Tracy Adams', \n",
    "                  'Lebo Sinuka', 'Lauren Pierce', 'Monika Bond', \n",
    "                 'Natahs Allsopp', 'Nicolas Winter', \n",
    "                 'Christopher Eckson', 'Siobhan O\\'Malley'],\n",
    "       'Annual' : [23, 20, 15, 19, 21, 21, 10, 15, 16, 23],\n",
    "       'Sick' : [10, 8, 10, 9, 7, 10, 9, 10, 8, 5],\n",
    "       'Personal' : [5, 4, 5, 0, 5, 2, 5, 4, 2, 5],\n",
    "       'Bonus' : [3, 0, 0, 3, 3, 6, 0, 3, 6, 3],\n",
    "       'Total leave taken' : [0, 3, 5, 10, 5, 8, 11, 9, 15, 5],\n",
    "       'Total leave available' : [38, 32, 30, 28, 33, 33, 24, 29, 26, 33],\n",
    "       'Annual total' : [38, 35, 35, 38, 38, 41, 35, 38, 41, 38]}\n",
    "\n",
    "# assign index\n",
    "row_labels = [215, 216, 217, 218, 219, 220, 221, 222, 223, 224]\n",
    "\n",
    "# create the DataFrame (indicating column names and index)\n",
    "leave_cycle = pd.DataFrame(data, columns = ['Name', 'Annual', 'Sick', \n",
    "                                           'Personal', 'Bonus', \n",
    "                                           'Total leave taken', \n",
    "                                           'Total leave available', \n",
    "                                           'Annual total'],\n",
    "                          index = row_labels)\n",
    "\n",
    "# specify the name of the index\n",
    "leave_cycle.index.name = 'Personnel_ID'\n",
    "\n",
    "leave_cycle"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "28ff7a7c",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
